[2025-10-22T21:15:29.583Z] [ERROR] relation "users" does not exist {
  status: 500,
  stack: 'error: relation "users" does not exist\n' +
    '    at C:\\Users\\Javier Parra\\Documents\\mvp-gis-n8n\\apps\\backend\\gis_mvp\\node_modules\\pg-pool\\index.js:45:11\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async findByEmail (C:\\Users\\Javier Parra\\Documents\\mvp-gis-n8n\\apps\\backend\\gis_mvp\\src\\repositories\\userRepository.ts:6:22)\n' +
    '    at async register (C:\\Users\\Javier Parra\\Documents\\mvp-gis-n8n\\apps\\backend\\gis_mvp\\src\\controllers\\authController.ts:34:26)'
}
